export const TOSS_PAYMENTS_CLIENT_KEY = process.env.NEXT_PUBLIC_TOSS_PAYMENTS_CLIENT_SECRET_KEY!;
export const TOSS_PAYMENTS_CUSTOMER_KEY_SECRET_KEY = process.env.NEXT_PUBLIC_TOSS_PAYMENTS_CUSTOMER_KEY_SECRET_KEY!;
export const API_URL = process.env.NEXT_PUBLIC_API_URL!;